### ISSUE TITLE
Create default time axis for Sequence

### ISSUE THREAD

**Issue by psomhorst** [EIT-ALIVE/eitprocessing#188]
Sequences don't have time axes, making slicing by index impractical: each dataset within the sequence can have different couplings between indices and time (and IntervalData has no concept of a coupling between indices and time). 

By defining a default time axis for the sequence, it becomes possible to slice a sequence by index. The following should happen:
- A start (closed), open end and closed end time is selected from the default time axis (if slicing from 10:20, start time = time[10], open end time = time[20] and closed end time = time[19].
- Each dataset within the sequence is sliced using the start and open end time
- Except interval data: they are sliced using the start and closed end times.

This will result in all datasets having time axes falling within the `[start, end)` interval.

**Comment by DaniBodor** [comment]
I've been rethinking this. 
In an offline discussion, we decided that when slicing by time, we want to have the default behavior be `[start, end)`, as you mention above, but allow for the option to add (or remove) additional time points on either side of this. This is mainly to solve the problem of allowing for e.g. `(start, end)` or `[start, end]` intervals when the time interval is unknown (i.e. removing one time point at the start or adding one time point at the end). This becomes very tricky when different objects in a `Sequence` have different time axes. 

Let's say I want to slice [0.0, 2.0] in a `Sequence` that contains `Dataset1` with an interval of 0.1 (the default) and `Dataset2` with an interval of of 0.3. I could say
```python
start = 0.0
end = 2.0
add_extra = (0,1)  #the idea being that it should be 2.0 inclusive
```
This works fine for `Dataset1`, which will have 21 time points, ranging from 0 to 2.0 (inclusive).
For `Dataset2`, however, it is still ambiguous whether the last time point should be 1.8 (the last time point that falls within the default axis up to 2.0) or 2.1 (ensuring it is 2.0 inclusive for all datasets). In the latter case, it would also be ambiguous whether to stop `Dataset1` at time point 2.0 or 2.1.

Given this, I am now reconsidering whether we want to give `Sequence` its own time axis after all. This can still be done by associating the time-axis of a dataset contained in the `Sequence` to it, which is now copied into `Sequence` as its own time axis (for example by creating a method `use_time_axis_of()` or something similar). Alternatively, a `Sequence` object can receive its own unique time axis (I guess using `np.linspace`). We would still need to consider whether an existing time-axis can be overwritten or whether this needs to be set when the `Sequence` is first created.
Slicing a `Sequence` by time (or index, for that matter), then, explicitly refers to the time axis of a `Sequence`, while slicing any particular dataset would refer to the time axis of that specific dataset.

**Comment by psomhorst** [comment]
Would this issue be solved by allowing slicing using open, closed, or half-open intervals?

As in you example, `dataset1` has time intervals of 0.1, while `dataset2` has intervals of 0.3. Both have 0 as minimum value and 6 as maximum value.

(Nomenclature for intervals from https://en.wikipedia.org/wiki/Interval_(mathematics)#Definitions_and_terminology)

```python
sequence.select_by_time(0, 2, interval="right-open")  # right-open slicing is normal for other Python objects 
# dataset1.time: [0, ..., 1.9], dataset2.time: [0, ..., 1.8]

sequence.select_by_time(0, 2, interval="left-open")
# dataset1.time: [0.1, ..., 2.0), dataset2.time: [0.3, ..., 1.8]

sequence.select_by_time(0, 2, interval="open")
# dataset1.time: [0.1, ..., 1.9], dataset2.time: [0.3, ..., 1.8]

sequence.select_by_time(0, 2, interval="closed")
# dataset1.time: [0, ..., 2.0], dataset2.time: [0, ..., 1.8]
```

This should have no impact if the start or end is `None`:

```python
sequence.select_by_time(0, None, interval="open")
# dataset1.time: [0.1, ..., 6.0], dataset2.time: [0.3, ..., 6.0]

sequence.select_by_time(None, 2, interval="open")
# dataset1.time: [0, ..., 1.9], dataset2.time: [0, ..., 1.8]
```

I think it would still be useful to add the option to add one or more timepoint(s). E.g.:

```python
sequence.select_by_time(1.0, None, interval="open", add_extra=(1, 0))  # guarantees the time starts on or before 1.0
# dataset1.time: [1.0, ..., 6.0], dataset2.time: [0.9, ..., 6.0]
```

I think this solves all issues. Except the new issue: introducing the term "interval" while also having `IntervalData` classes.

**Comment by DaniBodor** [comment]
I think it definitely helps clarify what the expected result is, but still doesn't fully solve all problems.
Especially in your last 2 examples, I find it odd that the sliced `dataset2` contains a time point that did exist in the original `dataset1` but not in the sliced one. Especially if `dataset1` is the primary associated time axis of `sequence`.

In my mind, if I use `select_by_time` on a `Sequence` (or on any other object, but I think the problem will mainly arise for `Sequence`), no matter what the parameters are, I expect that there is now a physical time range (which I may or may not know the exact limits of) that is used to slice all associated objects by.

Also, we are actually defining `select_by_time` as a manipulation that can only be performed on an object that contains a time axis, which would exclude `Sequence` instances. I see 3 options to resolve this:
1. Remove the requirement of a time axis --> not a fan of this, because the requirement makes sense.
2. Make an exception for `Sequence` --> not ideal, because adding exceptions removes clarity.
3. Give `Sequence` a time axis --> I don't remember whether we had a good argument to remove it, apart from the fact that we felt it wasn't strictly needed in the new structure. (Note that each dataset would still have its own time axis as well and not be resampled, which I think was our main objection to having a common time axis).

NB: I don't think that having a keyword `interval` here and an unrelated `IntervalData` class would lead to much confusion. Otherwise, we could call it something like `edge_behavior` and change "open/closed" to "inclusive/exclusive".

**Comment by DaniBodor** [comment]
I actually ran into another snag while working on this.

Currently, slicing (even by index) and concatenating a `Sequence` are not inverse operations. I'm not sure exactly what is going wrong yet, but my best guess so far is that it has to do with where things get sliced and how they get put back together again afterwards. 
I think this would also be solved or simplified by having a unique time axis to refer to when performing operations.

Note that this problem will def be more complex when `IntervalData` is introduced and we sliced into it. We may need some "memory" attribute or something that tells us what the original interval was, and if it's concatenated back together, it will know to merge that back into a single interval.

**Comment by psomhorst** [comment]
> Currently, slicing (even by index) and concatenating a `Sequence` are not inverse operations. I'm not sure exactly what is going wrong yet, but my best guess so far is that it has to do with where things get sliced and how they get put back together again afterwards. I think this would also be solved or simplified by having a unique time axis to refer to when performing operations.

I have checked this quite a few times, and always got the same data. Did you check `derived_from` is not included in the comparison. They will differ. 


> Note that this problem will def be more complex when `IntervalData` is introduced and we sliced into it. We may need some "memory" attribute or something that tells us what the original interval was, and if it's concatenated back together, it will know to merge that back into a single interval.

We already have: the `derived_from` attribute should tell us where data came from. If two Intervals from the same source with the same interval are merged, we might consider merging them into a single timepoint. 

I'm not 100% sure this will be a strict requirement, though. Maybe if we can be sure the interval data covers the entire time range (i.e. it never has no value), this should be doable. In other cases, it becomes harder to do this.

**Comment by DaniBodor** [comment]
> > Currently, slicing (even by index) and concatenating a `Sequence` are not inverse operations. I'm not sure exactly what is going wrong yet, but my best guess so far is that it has to do with where things get sliced and how they get put back together again afterwards. I think this would also be solved or simplified by having a unique time axis to refer to when performing operations.
> 
> I have checked this quite a few times, and always got the same data. Did you check `derived_from` is not included in the comparison. They will differ.

Good point! It was actually a combination of things. On the one hand indeed the `derived_from` attribute was the problem for continuous data. The other problem is the `phases`, which are currently associated to an index. Just removing the index led to other problems, which should be solvable, but not at 1am...


> > Note that this problem will def be more complex when `IntervalData` is introduced and we sliced into it. We may need some "memory" attribute or something that tells us what the original interval was, and if it's concatenated back together, it will know to merge that back into a single interval.
> 
> We already have: the `derived_from` attribute should tell us where data came from. If two Intervals from the same source with the same interval are merged, we might consider merging them into a single timepoint.

Good point, hadn't considered that.

> I'm not 100% sure this will be a strict requirement, though. Maybe if we can be sure the interval data covers the entire time range (i.e. it never has no value), this should be doable. In other cases, it becomes harder to do this.

I'm not sure what this comment is referring to

**Comment by psomhorst** [comment]
> The other problem is the `phases`, which are currently associated to an index. Just removing the index led to other problems, which should be solvable, but not at 1am...

Phases will disappear soon as part of #168. I think it's not worth solving that issue now.

> > I'm not 100% sure this will be a strict requirement, though. Maybe if we can be sure the interval data covers the entire time range (i.e. it never has no value), this should be doable. In other cases, it becomes harder to do this.
> 
> I'm not sure what this comment is referring to

This was a bit unclear, sorry. What I meant is that I'm not 100% sure it would be a requirement to have IntervalData match exactly when slicing and concatenating. 

If we know IntervalData is expected to cover the entire time range (i.e. a ventilator setting; there is no time point where there is no value for a setting), we could pad the time range when concatenating. 

E.g.: we have 10 seconds of recording with PEEP set to 10 for the first 5 seconds ([0, 4.9]) and set to 15 for the last 5 seconds ([5, 9.9]). So this IntervalData object has two time ranges and two values. 
When slicing (0-3), (3-5) and (5, 10) seconds, doing some calculation and then concatenating again, we would have three time ranges and associated values in the IntervalData object, in the ranges [0, 2.9], [3.0, 4.9] and [5, 9.9]. 
We could then merge the first two together because they have the same value, we know a PEEP has to be set during the entire period (this should be indicating when creating/loading the data), and there is no (significant) gap between the time ranges.

'no (significant) gap' is difficult to express formally, because there is no time delta or indices to match up. 
We could choose to attach a sample frequency to the IntervalData object, but this does not really make sense to me. 
An alternative approach is to not slice with a open end, but with a closed end. Then we will get [0, 3.0], [3.0, 5.0] and [5, 10], which are more easily concatenated. It is not too difficult to explain a time range runs until the end of a 'time point' (the end of 4.9), which is 5.0.

**Comment by psomhorst** [comment]
> I think it definitely helps clarify what the expected result is, but still doesn't fully solve all problems. Especially in your last 2 examples, I find it odd that the sliced `dataset2` contains a time point that did exist in the original `dataset1` but not in the sliced one. Especially if `dataset1` is the primary associated time axis of `sequence`.
> 
> In my mind, if I use `select_by_time` on a `Sequence` (or on any other object, but I think the problem will mainly arise for `Sequence`), no matter what the parameters are, I expect that there is now a physical time range (which I may or may not know the exact limits of) that is used to slice all associated objects by.
> 
> Also, we are actually defining `select_by_time` as a manipulation that can only be performed on an object that contains a time axis, which would exclude `Sequence` instances. I see 3 options to resolve this:
> 
> 1. Remove the requirement of a time axis --> not a fan of this, because the requirement makes sense.
> 2. Make an exception for `Sequence` --> not ideal, because adding exceptions removes clarity.
> 3. Give `Sequence` a time axis --> I don't remember whether we had a good argument to remove it, apart from the fact that we felt it wasn't strictly needed in the new structure. (Note that each dataset would still have its own time axis as well and not be resampled, which I think was our main objection to having a common time axis).
> 
> NB: I don't think that having a keyword `interval` here and an unrelated `IntervalData` class would lead to much confusion. Otherwise, we could call it something like `edge_behavior` and change "open/closed" to "inclusive/exclusive".

We already decided on 3., right? 

We can then easily make sure any object within a Sequence does not have any datapoint outside the sliced time range:
- slice sequence.time as indicated (open, half-open or closed)
- get the first and last time point as a new closed start and closed end time
- slice all objects within the sequence using a closed interval with the new start and end time

For example: we have a sequence with the main time axis from EIT data with a time delta of 0.1, and other continuous data with a time delta of 0.3.

```python
new_sequence = sequence.select_by_time(3, 6, "open")
new_sequence.time  # [3.1, ..., 5.9]
new_sequence.continuous_data['other'].time  # [3.3, ..., 5.7]

new_sequence = sequence.select_by_time(3, 6, "closed")
new_sequence.time  # [3.0, ..., 6.0]
new_sequence.continuous_data['other'].time  # [3.0, ..., 6.0]

new_sequence = sequence.select_by_time(2, 4, "closed")
new_sequence.time  # [2.0, ..., 4.0]
new_sequence.continuous_data['other'].time  # [2.1, ..., 3.9]
```
